# m32 or m64
if (ARCH_32)
    set(CMAKE_CXX_FLAGS " -v -m32 ${CMAKE_CXX_FLAGS}")
    set(CMAKE_C_FLAGS " -v -m32 ${CMAKE_C_FLAGS}")
    if(APHROC_VERBOSE_MESSAGES)
        message(STATUS "Building 32bit architecture")
    endif()
else(ARCH_32)
    set(CMAKE_CXX_FLAGS " -v -m64 ${CMAKE_CXX_FLAGS}")
    set(CMAKE_C_FLAGS " -v -m64 ${CMAKE_C_FLAGS}")
    if(APHROC_VERBOSE_MESSAGES)
        message(STATUS "Building 64bit architecture")
    endif()
endif(ARCH_32)
